XGBoost:
  max_depth: 6
  learning_rate: 0.05
  reg_alpha: 7
  reg_lambda: 5.3
  gamma: 0.3
  subsample: 0.8
  colsample_bytree: 0.5
  min_child_weight: 4

training:
  num_boost_round: 2000
  early_stopping_rounds: 30
  n_folds: 2
  random_seed: 42
  n_jobs: 2