artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gowtham-dd/Datasets/raw/main/Fertilizer_Pred.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  train_data_path: artifacts/data_ingestion/Fertilizer_Pred/train.csv
  original_data_path: artifacts/data_ingestion/Fertilizer_Pred/Fertilizer Prediction.csv
