artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gowtham-dd/Datasets/raw/main/Fertilizer_Pred.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  train_data_path: artifacts/data_ingestion/Fertilizer_Pred/train.csv
  original_data_path: artifacts/data_ingestion/Fertilizer_Pred/Fertilizer Prediction.csv

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_ingestion/Fertilizer_Pred/train.csv
  original_data_path: artifacts/data_ingestion/Fertilizer_Pred/Fertilizer Prediction.csv
  transformed_train_path: artifacts/data_transformation/transformed_train.csv
  transformed_original_path: artifacts/data_transformation/transformed_original.csv
  train_label_path: artifacts/data_transformation/train_labels.csv
  original_label_path: artifacts/data_transformation/original_labels.csv
  label_encoder_path: artifacts/data_transformation/label_encoder.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/transformed_train.csv
  original_data_path: artifacts/data_transformation/transformed_original.csv
  train_label_path: artifacts/data_transformation/train_labels.csv
  original_label_path: artifacts/data_transformation/original_labels.csv
  model_dir: artifacts/model_trainer/models
  model_name: xgb_model.bin